version: 2

models:
  - name: stg_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_order
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customer')
              field: customer_id          
      - name: order_priority
        tests:
          - accepted_values:
              values: ['1-URGENT', '2-HIGH', '3-MEDIUM', '4-NOT SPECIFIED', '5-LOW']

  - name: stg_nation
    columns:
      - name: nation_id
        tests:
          - unique
          - not_null
