version: 2

sources:
  - name: sf
    schema: TPCH_SF1
    database: SNOWFLAKE_SAMPLE_DATA
    loader: ADF
    # freshness: # default freshness
    #   warn_after: {count: 12, period: hour}
    #   error_after: {count: 24, period: hour}
    # loaded_at_field: loaded_at
    tables:
      - name: customer
        description: "Customers from source system ABC"
        identifier: CUSTOMER
        columns:
          - name: C_CUSTKEY
            description: "The Primary Key"
          - name: C_NAME
            description: "The name of the customer"        

      - name: order
        description: "Customer orders from source system ABC"
        identifier: ORDERS
        columns:
          - name: O_ORDERKEY
            description: "The Primary Key"
          - name: O_CUSTKEY
            description: "The Customer Foreign Key"  

      - name: nation
        description: "Nations from source system ABC"
        identifier: NATION
        columns:
          - name: N_NATIONKEY
            description: "The Primary Key"
          - name: N_NAME
            description: "The name of the Nation"  